DROP TABLE IF EXISTS CARTA_JUGADOR;
DROP TABLE IF EXISTS __EFMigrationsHistory;

DROP TABLE IF EXISTS Cartas;
DROP TABLE IF EXISTS Administradores;
DROP TABLE IF EXISTS PAISES;
DROP TABLE IF EXISTS Jugadores;

DROP TABLE IF EXISTS Auth;
DROP TABLE IF EXISTS Login;



