USE [StarDeck] 
GO

CREATE PROCEDURE GetCardsFromDeck
	@DecksId VARCHAR(14)
AS
BEGIN
	SELECT CARTAS.*
    FROM CARTAS
    INNER JOIN DECKS_CARTAS ON CARTAS.Id = DECKS_CARTAS.CartasId
    WHERE DECKS_CARTAS.DecksId = @DecksId
END

GO